name: Auto Release APK

on:
  push:
    branches:
      - main
    paths:
      - 'app/release/app-release.apk'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Version
        id: get_version
        run: |
          VERSION_NAME=$(grep 'versionName =' app/build.gradle.kts | awk -F'"' '{print $2}')
          VERSION_CODE=$(grep 'versionCode =' app/build.gradle.kts | awk '{print $3}')
          echo "VERSION=v${VERSION_NAME}.${VERSION_CODE}" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=Release v${VERSION_NAME} (Build ${VERSION_CODE})" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: ${{ steps.get_version.outputs.RELEASE_NAME }}
          files: app/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
